//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminMessage
    {
        public int Id { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole wymagane")]
        [DataType(DataType.MultilineText)]
        public string Content { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole wymagane")]
        public string Title { get; set; }
        public Nullable<bool> MainPage { get; set; }
    }
}
