//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public System.DateTime BorrowDate { get; set; }
        public int UserId { get; set; }
        public string BorrowState { get; set; }
    
        public virtual BookSpecimen BookSpecimen { get; set; }
        public virtual Users Users { get; set; }
    }
}
