//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Search
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DateOfSearch { get; set; }
        public int UserId { get; set; }
    }
}
